# Stage 1: Install dependencies + build
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

# NEXT_PUBLIC_* vars are bundled at build time — inject via build args
ARG NEXT_PUBLIC_DEFAULT_WEIGHT_SIMILARITY=4
ARG NEXT_PUBLIC_DEFAULT_WEIGHT_POPULARITY=3
ARG NEXT_PUBLIC_DEFAULT_WEIGHT_RATING=2
ARG NEXT_PUBLIC_DEFAULT_WEIGHT_RECENCY=1
ARG NEXT_PUBLIC_DEFAULT_HALF_LIFE_DAYS=1825
ARG NEXT_PUBLIC_DEFAULT_MIN_RELEASE_DATE=2000-01-01
ARG NEXT_PUBLIC_DEFAULT_MIN_REVIEW_COUNT=100
ARG NEXT_PUBLIC_DEFAULT_MIN_POSITIVE_PERCENT=50
ARG NEXT_PUBLIC_DEFAULT_RECOMMEND_COUNT=10

ENV NEXT_PUBLIC_DEFAULT_WEIGHT_SIMILARITY=$NEXT_PUBLIC_DEFAULT_WEIGHT_SIMILARITY
ENV NEXT_PUBLIC_DEFAULT_WEIGHT_POPULARITY=$NEXT_PUBLIC_DEFAULT_WEIGHT_POPULARITY
ENV NEXT_PUBLIC_DEFAULT_WEIGHT_RATING=$NEXT_PUBLIC_DEFAULT_WEIGHT_RATING
ENV NEXT_PUBLIC_DEFAULT_WEIGHT_RECENCY=$NEXT_PUBLIC_DEFAULT_WEIGHT_RECENCY
ENV NEXT_PUBLIC_DEFAULT_HALF_LIFE_DAYS=$NEXT_PUBLIC_DEFAULT_HALF_LIFE_DAYS
ENV NEXT_PUBLIC_DEFAULT_MIN_RELEASE_DATE=$NEXT_PUBLIC_DEFAULT_MIN_RELEASE_DATE
ENV NEXT_PUBLIC_DEFAULT_MIN_REVIEW_COUNT=$NEXT_PUBLIC_DEFAULT_MIN_REVIEW_COUNT
ENV NEXT_PUBLIC_DEFAULT_MIN_POSITIVE_PERCENT=$NEXT_PUBLIC_DEFAULT_MIN_POSITIVE_PERCENT
ENV NEXT_PUBLIC_DEFAULT_RECOMMEND_COUNT=$NEXT_PUBLIC_DEFAULT_RECOMMEND_COUNT

RUN npm run build

# Stage 2: Lightweight production runner
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

# Copy only the standalone output
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]
